# Top-level Makefile
# Builds everything: atmosphere, hydrosphere, Python interface and CLI interface

# TODO: don't always enable debugging
#CFLAGS = -ggdb -Wall -fPIC -std=c++11 -Ilib -Iatmosphere -Ihydrosphere -Itinyxml2 -fopenmp
# -MMD -MP emits a .d file per object listing the headers it includes, so editing a
# header rebuilds every .cpp that includes it. Without them make only ever saw the
# .cpp timestamps, and since nearly all the physics in this tree lives in headers,
# a header edit produced a link of stale objects that looked like a successful build.
# Ported from ATHAD.
CFLAGS = -ggdb -Wall -ffast-math -march=native -fPIC -std=c++17 -Ilib -Iatmosphere -Ihydrosphere -Itinyxml2 -fopenmp -MMD -MP

# Common files for the shared lib(libatom.a)
LIB_OBJ = lib/Array.o lib/Array_2D.o lib/Array_1D.o lib/Config.o lib/Utils.o lib/FFT.o

ATM_OBJ = atmosphere/cAtmosphereModel.o atmosphere/PrintMsg_Atm.o \
atmosphere/FileIO_Atm.o atmosphere/RHS_Atm_Turb.o \
atmosphere/RungeKutta_Atm_Turb.o atmosphere/MinMax_Atm.o \
atmosphere/Paraview_Atm.o atmosphere/InitValues_Atm.o \
atmosphere/Results_Atm.o

HYD_OBJ = hydrosphere/cHydrosphereModel.o hydrosphere/PrintMsg_Hyd.o \
hydrosphere/FileIO_Hyd.o hydrosphere/RHS_Hyd_Turb.o \
hydrosphere/RungeKutta_Hyd_Turb.o hydrosphere/MinMax_Hyd.o \
hydrosphere/Paraview_Hyd.o  hydrosphere/InitValues_Hyd.o \
hydrosphere/Results_Hyd.o

XML_OBJ = tinyxml2/tinyxml2.o

# Command line objects
ATM_CLI_OBJ = cli/atm.o cli/DefaultStream.o

HYD_CLI_OBJ = cli/hyd.o cli/DefaultStream.o

# Because there are so many parameters, many of the files are autogenerated
PARAM_OUTPUTS = atmosphere/AtmParameters.h hydrosphere/HydParameters.h atmosphere/AtmParameters.cpp  \
hydrosphere/HydParameters.cpp atmosphere/cAtmosphereDefaults.cpp.inc atmosphere/AtmosphereLoadConfig.cpp.inc \
atmosphere/AtmosphereParams.h.inc hydrosphere/HydrosphereDefaults.c.inc hydrosphere/HydrosphereLoadConfig.cpp.inc \
hydrosphere/HydrosphereParams.h.inc python/atmosphere_params.pxi python/hydrosphere_params.pxi \
python/atmosphere_pxd.pxi python/hydrosphere_pxd.pxi examples/config_atm.xml examples/config_hyd.xml python/pyatom.pyx

COPY_FILE = pyatom.so
TARGET_DIR = python

target = $(addprefix $(TARGET_DIR)/,$(COPY_FILE))

all: atm hyd python $(target)

libatom.a: $(PARAM_OUTPUTS) $(LIB_OBJ) $(ATM_OBJ) $(HYD_OBJ) $(XML_OBJ)
	ar rcs libatom.a $(LIB_OBJ) $(ATM_OBJ) $(HYD_OBJ) $(XML_OBJ)

atm: libatom.a $(ATM_CLI_OBJ)
	$(CXX) $(CFLAGS) $(ATM_CLI_OBJ) -L. -latom $(cFLAGS) -o cli/atm

hyd: libatom.a $(HYD_CLI_OBJ)
	$(CXX) $(CFLAGS) $(HYD_CLI_OBJ) -L. -latom $(cFLAGS) -o cli/hyd

$(PARAM_OUTPUTS): param.py
	rm -f atmosphere/cAtmosphereModel.o hydrosphere/cHydrosphereModel.o
	python param.py

analyze:
	analyze-build make

python: libatom.a python/pyatom.so

python/pyatom.so: python/pyatom.pyx python/atom.pxd libatom.a
	cd python && python setup.py build_ext --inplace

atmosphere/%.o: atmosphere/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

hydrosphere/%.o: hydrosphere/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

lib/%.o: lib/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

cli/%.o: cli/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

tinyxml2/%.o: tinyxml2/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

%.o: %.cpp
	$(CXX) $(CFLAGS) -c $<

# Header dependencies emitted by -MMD, one .d per object. The '-' suppresses the
# "no such file" noise on the first build, before any .d exists.
DEPS = $(LIB_OBJ:.o=.d) $(ATM_OBJ:.o=.d) $(HYD_OBJ:.o=.d) $(XML_OBJ:.o=.d) \
       $(ATM_CLI_OBJ:.o=.d) $(HYD_CLI_OBJ:.o=.d)
-include $(DEPS)

# EVERY OBJECT DEPENDS ON THIS MAKEFILE, and the reason is a bug that got past the -MMD
# repair above. Header tracking only covers objects that have ALREADY been compiled with
# -MMD; an object built before it has no .d, so make sees only its .cpp and never rebuilds
# it. cli/atm.o was in exactly that state, and because it holds `cAtmosphereModel model;` as
# a STACK LOCAL, main reserved the OLD sizeof while libatom.a constructed the NEW one --
# the constructor ran off the end of main's frame and tripped the stack canary at exit
# (*** stack smashing detected ***), with no compiler warning anywhere. A Makefile change is
# exactly the moment that hazard exists, so tie every object to it.
$(LIB_OBJ) $(ATM_OBJ) $(HYD_OBJ) $(XML_OBJ) $(ATM_CLI_OBJ) $(HYD_CLI_OBJ): Makefile

.PHONY: clean
clean:
	\rm -vf $(LIB_OBJ) $(ATM_OBJ) $(HYD_OBJ) $(XML_OBJ) $(ATM_CLI_OBJ) $(HYD_CLI_OBJ) $(DEPS) $(PARAM_OUTPUTS) atm hyd libatom.a
	\rm -vf python/*.so python/*.o python/pyatom.cpp
	\rm -rf python/build/
