# Top-level Makefile
# Builds everything: cube, Python interface 

# TODO: don't always enable debugging
CFLAGS = -ggdb -Wall -ffast-math -march=native -fPIC -std=c++17 -Ilib -Icube -fopenmp

# Common files for the shared lib(libcube.a)
LIB_OBJ = lib/Array.o lib/Array_2D.o lib/Array_1D.o lib/Utils.o

CUBE_OBJ = cube/cCubeModel.o cube/CubeParameters.o \
cube/PrintMsg_Cube.o \
cube/FileIO_Cube.o cube/RHS_Cube_Turb.o \
cube/RungeKutta_Cube_Turb.o cube/MinMax_Cube.o \
cube/Paraview_Cube.o \
cube/Results_Cube.o


# Command line objects
CUBE_CLI_OBJ = cli/cube.o cli/DefaultStream.o

# Because there are so many parameters, many of the files are autogenerated
PARAM_OUTPUTS = cube/CubeParameters.h cube/CubeParameters.cpp \

COPY_FILE = pycube.so
TARGET_DIR = python

target = $(addprefix $(TARGET_DIR)/,$(COPY_FILE))

all: cube python $(target)

libcube.a: $(PARAM_OUTPUTS) $(LIB_OBJ) $(CUBE_OBJ)
	ar rcs libcube.a $(LIB_OBJ) $(CUBE_OBJ)

cube: libcube.a $(CUBE_CLI_OBJ)
	$(CXX) $(CFLAGS) $(CUBE_CLI_OBJ) -L. -lcube $(cFLAGS) -o cli/cube

$(PARAM_OUTPUTS): param.py
	rm -f cube/cCubeModel.o
	python param.py

analyze:
	analyze-build make

python: libcube.a python/pycube.so

python/pycube.so: python/pycube.pyx python/cube.pxd libcube.a
	cd python && python setup.py build_ext --inplace

cube/%.o: cube/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

lib/%.o: lib/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

cli/%.o: cli/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

%.o: %.cpp
	$(CXX) $(CFLAGS) -c $<

.PHONY: clean
clean:
	\rm -vf $(LIB_OBJ) $(CUBE_OBJ) $(XML_OBJ) $(CUBE_CLI_OBJ) $(PARAM_OUTPUTS) libcube.a
	\rm -vf python/*.so python/*.o python/pycube.cpp
	\rm -rf python/build/
