// cube/CubeParameters.cpp
// THIS FILE IS AUTOMATICALLY GENERATED BY param.py
// ANY CHANGES WILL BE OVERWRITTEN AT COMPILE TIME

#include "cCubeModel.h"

void cCubeModel::SetDefaultConfig() {

    // common section
    output_path = "output_ATOM_Cube_Turbulence/";
    verbose = false;
    paraview_panorama_vts_flag = true;
    L_atm = 1.0;
    p_0 = 1013.25;
    sigma = 5.67028e-8;
    eps_residuum = 0.0001;
    turb_model = "k_omega_SST";

    // cube section
    nm = 1120;
    checkpoint = 112;
    panorama_print = 560;
    re = 1000.0;
    pr = 0.7179;
    pr_turb = 0.9;
    R_Air = 286.9;
    u_0 = 1.0;

}
