// cube/CubeParameters.h
// THIS FILE IS AUTOMATICALLY GENERATED BY param.py
// ANY CHANGES WILL BE OVERWRITTEN AT COMPILE TIME

    // common section
    std::string output_path;  // directory where model outputs should be placed (must end in /)
    bool verbose;  // enable verbose diagnostic output
    bool paraview_panorama_vts_flag;  // flag to control if create paraview panorama
    double L_atm;  // extension of the atmosphere shell in m, Benocci
    double p_0;  // pressure at sea level in hPa
    double sigma;  // Stefan-Boltzmann constant W/(m²*K4)
    double eps_residuum;  // relative error, end of iterations reached, 1% error allowed
    std::string turb_model;  // turbulence model: none, k_epsilon, k_omega, k_omega_SST

    // cube section
    int nm;  // the maximum number of iterations
    int checkpoint;  // control when to write output files
    int panorama_print;  // control when to write panorama files
    double re;  // Reynolds number for laminar flows
    double pr;  // Prandtl number of air for laminar flows
    double pr_turb;  // turbulent Prandtl number for temperature transport
    double R_Air;  // specific gas constant of air in J/(kg*K)
    double u_0;  // annual mean of surface wind velocity in m/s, Benocci

