# python/cube.pxd
# THIS FILE IS AUTOMATICALLY GENERATED BY param.py
# ANY CHANGES WILL BE OVERWRITTEN AT COMPILE TIME
from libcpp cimport bool
from libcpp.string cimport string
from libcpp.vector cimport vector

cdef extern from "cCubeModel.h":
    cppclass cCubeModel:
        cCubeModel() except +
        void LoadConfig(const char *filename)
        void Run()
        void RunTimeSlice(int time_slice)
        vector[float] get_layer_heights()
        # common section
        string output_path
        bool verbose
        bool paraview_panorama_vts_flag
        double L_atm
        double p_0
        double sigma
        double eps_residuum
        string turb_model
        # cube section
        int nm
        int checkpoint
        int panorama_print
        double re
        double pr
        double pr_turb
        double R_Air
        double u_0
