# pxd files
# THIS FILE IS AUTOMATICALLY GENERATED BY param.py
# ANY CHANGES WILL BE OVERWRITTEN AT COMPILE TIME
from libcpp.vector cimport vector
cdef extern from "cHydrosphereModel.h":
    cppclass cHydrosphereModel:
        cHydrosphereModel() except +  # NB! std::bad_alloc will be converted to MemoryError
        void LoadConfig(const char *filename)
        void Run()
        void RunTimeSlice(int time_slice)
        vector[float] get_layer_heights()
        # common section
        string output_path
        string bathymetry_path
        string BathymetrySuffix
        string config_xml_path
        bool verbose
        bool paraview_panorama_vts_flag
        double Coriolis
        double centrifugal
        double buoyancy
        double r_Earth
        double omega
        double g
        int time_start
        int time_end
        int time_step
        string velocity_v_file
        string velocity_w_file
        string temperature_file
        string precipitation_file
        string salinity_file
        string temperature_global_file
        string temperature_equat_file
        string temperature_pole_file
        string reconstruction_script_path
        bool use_earthbyte_reconstruction
        bool use_NASA_velocity
        bool use_NASA_temperature
        int Ma_switch
        int CategoryIceScheme
        double p_0
        double t_0
        double r_air
        double r_0_water
        double t_equat_modern
        double t_pole_modern
        double t_paleo_max
        double rad_equator
        double rad_pole
        double rad_equator_short
        double rad_pole_short
        double sigma
        double eps_residuum
        string turb_model
        int inviscid_spinup_iters
        int inviscid_ramp_iters
        int moist_phys_start_iter
        double dt_visc
        double dt_inviscid
        # hydrosphere section
        string input_path
        int nm
        int checkpoint
        int panorama_print
        int atm_transfer_iter
        string ocean_depth_mode
        double L_hyd
        double re
        double sc
        double pr
        double cp_w
        double c_35
        double u_0_wind
        double u_0
        double r_0_saltwater
        double t_pole_salt
        double co2_vegetation
        double co2_ocean
        double co2_land
