/* Generated by Cython 0.29.28 */

#ifndef __PYX_HAVE__pyatom
#define __PYX_HAVE__pyatom

#include "Python.h"

#ifndef __PYX_HAVE_API__pyatom

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void PythonPrint(char const *);

#endif /* !__PYX_HAVE_API__pyatom */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initpyatom(void);
#else
PyMODINIT_FUNC PyInit_pyatom(void);
#endif

#endif /* !__PYX_HAVE__pyatom */
