# python/pycube.pyx
# THIS FILE IS AUTOMATICALLY GENERATED BY param.py
# ANY CHANGES WILL BE OVERWRITTEN AT COMPILE TIME


import sys

from cube cimport cCubeModel

from libcpp cimport bool
from libcpp.string cimport string
from libcpp.vector cimport vector

class Model:
    """
    CubeModel Turbulence Model Object
    """
    def __init__( self ):
        self.cube = CubeModel()
        self.output_path = ""
        self.time_slice = 0
        self.config_xml = ""

    def run_cube ( self, t_s, output_path, cfg_xml ):
        self.time_slice = t_s
        self.output_path = output_path
        self.config_xml = cfg_xml
        print(self.time_slice)
        print(self.output_path)
        print(self.config_xml)
        self.cube.load_config ( self.config_xml )
        self.cube.run_time_slice ( self.time_slice )


cdef class CubeModel:
    """ 
    Cython wrapper class for C++ class CubeModel
    """
    cdef:
        cCubeModel *_thisptr

    def __cinit__(CubeModel self):
        # Initialize the "this pointer" to NULL so __dealloc__
        # knows if there is something to deallocate. Do not 
        # call new cCubeModel() here.
        self._thisptr = NULL
        
    def __init__(CubeModel self):
        # Constructing the C++ object might raise std::bad_alloc
        # which is automatically converted to a Python MemoryError
        # by Cython. We therefore need to call "new cCubeModel()" in
        # __init__ instead of __cinit__.
        self._thisptr = new cCubeModel() 

    def __dealloc__(CubeModel self):
        # Only call del if the C++ object is alive, 
        # or we will get a segfault.
        if self._thisptr != NULL:
            del self._thisptr
            
    cdef int _check_alive(CubeModel self) except -1:
        # Because of the context manager protocol, the C++ object
        # might die before PyCubeModel self is reclaimed.
        # We therefore need a small utility to check for the
        # availability of self._thisptr
        if self._thisptr == NULL:
            raise RuntimeError("Wrapped C++ object is deleted")
        else:
            return 0

    def load_config(CubeModel self, str filename):
        self._check_alive()
        self._thisptr.LoadConfig(filename.encode())
        return None
    
    def run(CubeModel self):
        self._check_alive()
        self._thisptr.Run()
        return None

    def run_time_slice(CubeModel self, int t):
        self._check_alive()
        self._thisptr.RunTimeSlice(t)
        return None

    def get_layer_heights(CubeModel self):
        self._check_alive()
        return self._thisptr.get_layer_heights()

    # common section
    property output_path:
        def __get__(CubeModel self):
            self._check_alive()
            return self._thisptr.output_path
    
        def __set__(CubeModel self, value):
            self._check_alive()
            self._thisptr.output_path = <string> value
    
    property verbose:
        def __get__(CubeModel self):
            self._check_alive()
            return self._thisptr.verbose
    
        def __set__(CubeModel self, value):
            self._check_alive()
            self._thisptr.verbose = <bool> value
    
    property paraview_panorama_vts_flag:
        def __get__(CubeModel self):
            self._check_alive()
            return self._thisptr.paraview_panorama_vts_flag
    
        def __set__(CubeModel self, value):
            self._check_alive()
            self._thisptr.paraview_panorama_vts_flag = <bool> value
    
    property L_atm:
        def __get__(CubeModel self):
            self._check_alive()
            return self._thisptr.L_atm
    
        def __set__(CubeModel self, value):
            self._check_alive()
            self._thisptr.L_atm = <double> value
    
    property p_0:
        def __get__(CubeModel self):
            self._check_alive()
            return self._thisptr.p_0
    
        def __set__(CubeModel self, value):
            self._check_alive()
            self._thisptr.p_0 = <double> value
    
    property sigma:
        def __get__(CubeModel self):
            self._check_alive()
            return self._thisptr.sigma
    
        def __set__(CubeModel self, value):
            self._check_alive()
            self._thisptr.sigma = <double> value
    
    property eps_residuum:
        def __get__(CubeModel self):
            self._check_alive()
            return self._thisptr.eps_residuum
    
        def __set__(CubeModel self, value):
            self._check_alive()
            self._thisptr.eps_residuum = <double> value
    
    property turb_model:
        def __get__(CubeModel self):
            self._check_alive()
            return self._thisptr.turb_model
    
        def __set__(CubeModel self, value):
            self._check_alive()
            self._thisptr.turb_model = <string> value
    
    # cube section
    property nm:
        def __get__(CubeModel self):
            self._check_alive()
            return self._thisptr.nm
    
        def __set__(CubeModel self, value):
            self._check_alive()
            self._thisptr.nm = <int> value
    
    property checkpoint:
        def __get__(CubeModel self):
            self._check_alive()
            return self._thisptr.checkpoint
    
        def __set__(CubeModel self, value):
            self._check_alive()
            self._thisptr.checkpoint = <int> value
    
    property panorama_print:
        def __get__(CubeModel self):
            self._check_alive()
            return self._thisptr.panorama_print
    
        def __set__(CubeModel self, value):
            self._check_alive()
            self._thisptr.panorama_print = <int> value
    
    property re:
        def __get__(CubeModel self):
            self._check_alive()
            return self._thisptr.re
    
        def __set__(CubeModel self, value):
            self._check_alive()
            self._thisptr.re = <double> value
    
    property pr:
        def __get__(CubeModel self):
            self._check_alive()
            return self._thisptr.pr
    
        def __set__(CubeModel self, value):
            self._check_alive()
            self._thisptr.pr = <double> value
    
    property pr_turb:
        def __get__(CubeModel self):
            self._check_alive()
            return self._thisptr.pr_turb
    
        def __set__(CubeModel self, value):
            self._check_alive()
            self._thisptr.pr_turb = <double> value
    
    property R_Air:
        def __get__(CubeModel self):
            self._check_alive()
            return self._thisptr.R_Air
    
        def __set__(CubeModel self, value):
            self._check_alive()
            self._thisptr.R_Air = <double> value
    
    property u_0:
        def __get__(CubeModel self):
            self._check_alive()
            return self._thisptr.u_0
    
        def __set__(CubeModel self, value):
            self._check_alive()
            self._thisptr.u_0 = <double> value
    

    # The context manager protocol allows us to precisely
    # control the liftetime of the wrapped C++ object. del
    # is called deterministically and independently of 
    # the Python garbage collection.

    def __enter__(CubeModel self):
        self._check_alive()
        return self
    
    def __exit__(CubeModel self, exc_tp, exc_val, exc_tb):
        if self._thisptr != NULL:
            del self._thisptr 
            self._thisptr = NULL # inform __dealloc__
        return False # propagate exceptions



cdef public void PythonPrint(const char *s):
    print(s.decode(), end='')
    sys.stdout.flush()
